// Code generated by candi v1.20.0.

package workerhandler

import (
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"ticketing/internal/modules/transaction/domain"
	"ticketing/pkg/helper"
	"ticketing/pkg/shared/usecase"

	"github.com/golangid/candi/candishared"
	taskqueueworker "github.com/golangid/candi/codebase/app/task_queue_worker"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/factory/types"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
)

// TaskQueueHandler struct
type TaskQueueHandler struct {
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewTaskQueueHandler constructor
func NewTaskQueueHandler(uc usecase.Usecase, deps dependency.Dependency) *TaskQueueHandler {
	return &TaskQueueHandler{
		uc:        uc,
		validator: deps.GetValidator(),
	}
}

// MountHandlers mount handler group
func (h *TaskQueueHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add(helper.ReserveTicket, h.handleTaskReserveTicket,
		types.WorkerHandlerOptionAddConfig(taskqueueworker.TaskOptionDeleteJobAfterSuccess, false),
	)
	group.Add(helper.SendEmail, h.handleTaskSendEmail,
		types.WorkerHandlerOptionAddConfig(taskqueueworker.TaskOptionDeleteJobAfterSuccess, false),
	)
	group.Add(helper.TaskGenerateTicketCode, h.handleTaskGenerateTicketCode,
		types.WorkerHandlerOptionAddConfig(taskqueueworker.TaskOptionDeleteJobAfterSuccess, false),
	)
}

func (h *TaskQueueHandler) handleTaskReserveTicket(eventContext *candishared.EventContext) error {
	trace, ctx := tracer.StartTraceWithContext(eventContext.Context(), "TransactionDeliveryTaskQueue:HandleTaskReserveTicket")
	defer trace.Finish()

	fmt.Printf("executing task '%s' has been %s retry, with message: %s\n",
		eventContext.HandlerRoute(),
		eventContext.Header()["retries"],
		eventContext.Message(),
	)

	var data domain.RequestTransaction
	if err := json.Unmarshal(eventContext.Message(), &data); err != nil {
		trace.SetError(err)
		return err
	}

	// exec usecase
	err := h.uc.Transaction().ReserveTicket(ctx, data)
	if err != nil {
		trace.SetError(err)
		return &candishared.ErrorRetrier{
			Delay:   10 * time.Second,
			Message: err.Error(),
		}
	}

	return nil
}

func (h *TaskQueueHandler) handleTaskSendEmail(eventContext *candishared.EventContext) error {
	trace, ctx := tracer.StartTraceWithContext(eventContext.Context(), "TransactionDeliveryTaskQueue:HandleTaskSendEmail")
	defer trace.Finish()

	fmt.Printf("executing task '%s' has been %s retry, with message: %s\n",
		eventContext.HandlerRoute(),
		eventContext.Header()["retries"],
		eventContext.Message(),
	)

	var data domain.ReqSendEmail
	if err := json.Unmarshal(eventContext.Message(), &data); err != nil {
		trace.SetError(err)
		return err
	}

	// exec usecase
	err := h.uc.Transaction().SendEmail(ctx, data)
	if err != nil {
		trace.SetError(err)
		return &candishared.ErrorRetrier{
			Delay:   10 * time.Second,
			Message: err.Error(),
		}
	}

	return nil
}

func (h *TaskQueueHandler) handleTaskGenerateTicketCode(eventContext *candishared.EventContext) error {
	trace, ctx := tracer.StartTraceWithContext(eventContext.Context(), "TransactionDeliveryTaskQueue:HandleTaskGenerateTicketCode")
	defer trace.Finish()

	fmt.Printf("executing task '%s' has been %s retry, with message: %s\n",
		eventContext.HandlerRoute(),
		eventContext.Header()["retries"],
		eventContext.Message(),
	)

	id, err := strconv.ParseInt(string(eventContext.Message()), 10, 64)
	if err != nil {
		trace.SetError(err)
		return err
	}

	// exec usecase
	err = h.uc.Transaction().GenerateTicketCode(ctx, id)
	if err != nil {
		trace.SetError(err)
		return &candishared.ErrorRetrier{
			Delay:   10 * time.Second,
			Message: err.Error(),
		}
	}

	return nil
}
