// Code generated by candi v1.20.0.

package repository

import (
	"context"
	"strings"
	"time"

	"ticketing/internal/modules/ticket/domain"
	"ticketing/pkg/shared"
	shareddomain "ticketing/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type ticketRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewTicketRepoSQL mongo repo constructor
func NewTicketRepoSQL(readDB, writeDB *gorm.DB) TicketRepository {
	return &ticketRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *ticketRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterTicket) (data []shareddomain.Ticket, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TicketRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterTicket(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *ticketRepoSQL) Count(ctx context.Context, filter *domain.FilterTicket) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TicketRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterTicket(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Ticket{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *ticketRepoSQL) Find(ctx context.Context, filter *domain.FilterTicket) (result shareddomain.Ticket, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TicketRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterTicket(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *ticketRepoSQL) Save(ctx context.Context, data *shareddomain.Ticket, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TicketRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = shared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *ticketRepoSQL) Delete(ctx context.Context, filter *domain.FilterTicket) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TicketRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterTicket(shared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Ticket{}).Error
	return
}

func (r *ticketRepoSQL) setFilterTicket(db *gorm.DB, filter *domain.FilterTicket) *gorm.DB {
	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where(`LOWER(title) LIKE '%%' || ? || '%%'`, strings.ToLower(filter.Search))
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
