// Code generated by candi v1.20.0.

package repository

import (
	"context"

	"ticketing/internal/modules/ticket/domain"
	shareddomain "ticketing/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// TicketRepository abstract interface
type TicketRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterTicket) ([]shareddomain.Ticket, error)
	Count(ctx context.Context, filter *domain.FilterTicket) int
	Find(ctx context.Context, filter *domain.FilterTicket) (shareddomain.Ticket, error)
	Save(ctx context.Context, data *shareddomain.Ticket, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterTicket) (err error)
}
