// Code generated by candi v1.20.0.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	transactionusecase "ticketing/internal/modules/transaction/usecase"
	ticketusecase "ticketing/internal/modules/ticket/usecase"
	"ticketing/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Transaction() transactionusecase.TransactionUsecase
		Ticket() ticketusecase.TicketUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		transactionusecase.TransactionUsecase
		ticketusecase.TicketUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.TransactionUsecase, setSharedUsecaseFunc = transactionusecase.NewTransactionUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.TicketUsecase, setSharedUsecaseFunc = ticketusecase.NewTicketUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Transaction() transactionusecase.TransactionUsecase {
	return uc.TransactionUsecase
}

func (uc *usecaseUow) Ticket() ticketusecase.TicketUsecase {
	return uc.TicketUsecase
}

