// Code generated by candi v1.20.0.

package repository

import (
	"context"

	"ticketing/internal/modules/transaction/domain"
	shareddomain "ticketing/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// TransactionRepository abstract interface
type TransactionRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterTransaction) ([]shareddomain.Transaction, error)
	Count(ctx context.Context, filter *domain.FilterTransaction) int
	Find(ctx context.Context, filter *domain.FilterTransaction) (shareddomain.Transaction, error)
	Save(ctx context.Context, data *shareddomain.Transaction, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterTransaction) (err error)
}
