// Code generated by candi v1.20.0.

package repository

import (
	"context"
	"strings"
	"time"

	"ticketing/internal/modules/transaction/domain"
	"ticketing/pkg/shared"
	shareddomain "ticketing/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type transactionRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewTransactionRepoSQL mongo repo constructor
func NewTransactionRepoSQL(readDB, writeDB *gorm.DB) TransactionRepository {
	return &transactionRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *transactionRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterTransaction) (data []shareddomain.Transaction, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TransactionRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterTransaction(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *transactionRepoSQL) Count(ctx context.Context, filter *domain.FilterTransaction) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TransactionRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterTransaction(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Transaction{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *transactionRepoSQL) Find(ctx context.Context, filter *domain.FilterTransaction) (result shareddomain.Transaction, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TransactionRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterTransaction(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *transactionRepoSQL) Save(ctx context.Context, data *shareddomain.Transaction, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TransactionRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = shared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *transactionRepoSQL) Delete(ctx context.Context, filter *domain.FilterTransaction) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "TransactionRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterTransaction(shared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Transaction{}).Error
	return
}

func (r *transactionRepoSQL) setFilterTransaction(db *gorm.DB, filter *domain.FilterTransaction) *gorm.DB {
	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.TicketID != nil {
		db = db.Where("ticket_id = ?", *filter.TicketID)
	}
	if filter.Status != "" {
		db = db.Where("status = ?", filter.Status)
	}
	if filter.Search != "" {
		db = db.Where(`(UPPER(customer_name) LIKE '%%' || ? || '%%' OR UPPER(customer_email) LIKE '%%' || ? || '%%')`, strings.ToUpper(filter.Search), strings.ToUpper(filter.Search))
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
