// Code generated by candi v1.20.0.

package usecase

import (
	"context"

	"ticketing/internal/modules/transaction/domain"
	"ticketing/pkg/shared/repository"
	"ticketing/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
)

// TransactionUsecase abstraction
type TransactionUsecase interface {
	GetAllTransaction(ctx context.Context, filter *domain.FilterTransaction) (data domain.ResponseTransactionList, err error)
	GetDetailTransaction(ctx context.Context, id int64) (data domain.ResponseTransaction, err error)
	CreateTransaction(ctx context.Context, data *domain.RequestTransaction) (err error)
	UpdateTransaction(ctx context.Context, data *domain.RequestTransaction) (err error)
	DeleteTransaction(ctx context.Context, id int64) (err error)
	ReserveTicket(ctx context.Context, req domain.RequestTransaction) (err error)
	SendEmail(ctx context.Context, req domain.ReqSendEmail) (err error)
	GenerateTicketCode(ctx context.Context, id int64) (err error)
}

type transactionUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	cache         interfaces.Cache
	// repoMongo     repository.RepoMongo
}

// NewTransactionUsecase usecase impl constructor
func NewTransactionUsecase(deps dependency.Dependency) (TransactionUsecase, func(sharedUsecase common.Usecase)) {
	uc := &transactionUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),

	}
	if redisPool := deps.GetRedisPool(); redisPool != nil {
		uc.cache = redisPool.Cache()
	}

	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
