// Code generated by candi v1.20.0.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	"ticketing/internal/modules/transaction/domain"
	"ticketing/pkg/helper"
	"ticketing/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	restserver "github.com/golangid/candi/codebase/app/rest_server"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Transaction := root.Group(candihelper.V1+"/transaction", h.mw.HTTPBasicAuth)

	v1Transaction.GET("/", h.getAllTransaction)
	v1Transaction.GET("/:id", h.getDetailTransactionByID)
	v1Transaction.POST("/", h.createTransaction)
	// v1Transaction.PUT("/:id", h.updateTransaction)
	// v1Transaction.DELETE("/:id", h.deleteTransaction)
}

// GetAllTransaction documentation
// @Summary			Get All Transaction
// @Description		API for get all transaction
// @Tags			Transaction
// @Accept			json
// @Produce			json
// @Param			page	query	string	false	"Page with default value is 1"
// @Param			limit	query	string	false	"Limit with default value is 10"
// @Param			search	query	string	false	"Search"
// @Param			order_by	query	string	false	"Order By"
// @Param			sort	query	string	false	"Sort (ASC DESC)"
// @Success			200	{object}	domain.ResponseTransactionList
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/transaction [get]
func (h *RestHandler) getAllTransaction(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TransactionDeliveryREST:GetAllTransaction")
	var (
		err    error
		filter domain.FilterTransaction
	)

	defer func() {
		trace.Log("filter", filter)
		trace.Finish(tracer.FinishWithError(err))
	}()

	if err := candihelper.ParseFromQueryParam(req.URL.Query(), &filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(rw)
		return
	}

	if err := h.validator.ValidateDocument("transaction/get_all", filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(rw)
		return
	}

	result, err := h.uc.Transaction().GetAllTransaction(ctx, &filter)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	message := "success"
	response := wrapper.NewHTTPResponse(http.StatusOK, message, result.Data)
	response.Meta = result.Meta
	response.JSON(rw)
}

// GetDetailTransaction documentation
// @Summary			Get Detail Transaction
// @Description		API for get detail transaction
// @Tags			Transaction
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Success			200	{object}	domain.ResponseTransaction
// @Success			400	{object}	wrapper.HTTPResponse
// @Success			404	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/transaction/{id} [get]
func (h *RestHandler) getDetailTransactionByID(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TransactionDeliveryREST:GetDetailTransactionByID")
	var (
		err error
		id  int64
	)

	defer func() {
		trace.Finish(tracer.FinishWithError(err))
	}()

	id, err = strconv.ParseInt(restserver.URLParam(req, "id"), 10, 64)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, helper.ErrorID).JSON(rw) //nolint:all
		return
	}

	data, err := h.uc.Transaction().GetDetailTransaction(ctx, id)
	if err != nil {
		if err.Error() == helper.RecordNotFound {
			wrapper.NewHTTPResponse(http.StatusNotFound, err.Error()).JSON(rw) //nolint:all
			return
		}
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "success", data).JSON(rw)
}

// CreateTransaction documentation
// @Summary			Create Transaction
// @Description		API for create transaction
// @Tags			Transaction
// @Accept			json
// @Produce			json
// @Param			data	body	domain.RequestTransaction	true	"Body Data"
// @Success			200	{object}	domain.ResponseTransaction
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/transaction [post]
func (h *RestHandler) createTransaction(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TransactionDeliveryREST:CreateTransaction")
	var (
		err     error
		payload domain.RequestTransaction
	)

	defer func() {
		trace.Log("payload", payload)
		trace.Finish(tracer.FinishWithError(err))
	}()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("transaction/save", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	err = h.uc.Transaction().CreateTransaction(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusCreated, "success").JSON(rw)
}

// UpdateTransaction documentation
// @Summary			Update Transaction
// @Description		API for update transaction
// @Tags			Transaction
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Param			data	body	domain.RequestTransaction	true	"Body Data"
// @Success			200	{object}	domain.ResponseTransaction
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/transaction/{id} [put]
func (h *RestHandler) updateTransaction(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TransactionDeliveryREST:UpdateTransaction")
	var (
		err error
		id  int64
	)

	defer func() {
		trace.Finish(tracer.FinishWithError(err))
	}()

	id, err = strconv.ParseInt(restserver.URLParam(req, "id"), 10, 64)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, helper.ErrorID).JSON(rw) //nolint:all
		return
	}

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("transaction/save", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	var payload domain.RequestTransaction
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	payload.ID = id
	err = h.uc.Transaction().UpdateTransaction(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "success").JSON(rw)
}

// DeleteTransaction documentation
// @Summary			Delete Transaction
// @Description		API for delete transaction
// @Tags			Transaction
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Success			200	{object}	domain.ResponseTransaction
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/transaction/{id} [delete]
func (h *RestHandler) deleteTransaction(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TransactionDeliveryREST:DeleteTransaction")
	var (
		err error
		id  int64
	)

	defer func() {
		trace.Finish(tracer.FinishWithError(err))
	}()

	id, err = strconv.ParseInt(restserver.URLParam(req, "id"), 10, 64)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, helper.ErrorID).JSON(rw) //nolint:all
		return
	}

	if err := h.uc.Transaction().DeleteTransaction(ctx, id); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "success").JSON(rw)
}
