// Code generated by candi v1.20.0.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	"ticketing/internal/modules/ticket/domain"
	"ticketing/pkg/helper"
	"ticketing/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	restserver "github.com/golangid/candi/codebase/app/rest_server"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Ticket := root.Group(candihelper.V1+"/ticket", h.mw.HTTPBasicAuth)

	v1Ticket.GET("/", h.getAllTicket)
	v1Ticket.GET("/:id", h.getDetailTicketByID)
	v1Ticket.POST("/", h.createTicket)
	v1Ticket.PUT("/:id", h.updateTicket)
	v1Ticket.DELETE("/:id", h.deleteTicket)
}

// GetAllTicket documentation
// @Summary			Get All Ticket
// @Description		API for get all ticket
// @Tags			Ticket
// @Accept			json
// @Produce			json
// @Param			page	query	string	false	"Page with default value is 1"
// @Param			limit	query	string	false	"Limit with default value is 10"
// @Param			search	query	string	false	"Search"
// @Param			order_by	query	string	false	"Order By"
// @Param			sort	query	string	false	"Sort (ASC DESC)"
// @Success			200	{object}	domain.ResponseTicketList
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/ticket [get]
func (h *RestHandler) getAllTicket(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TicketDeliveryREST:GetAllTicket")
	var (
		err    error
		filter domain.FilterTicket
	)

	defer func() {
		trace.Log("filter", filter)
		trace.Finish(tracer.FinishWithError(err))
	}()

	if err := candihelper.ParseFromQueryParam(req.URL.Query(), &filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(rw)
		return
	}

	if err := h.validator.ValidateDocument("ticket/get_all", filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(rw)
		return
	}

	result, err := h.uc.Ticket().GetAllTicket(ctx, &filter)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	message := "success"
	response := wrapper.NewHTTPResponse(http.StatusOK, message, result.Data)
	response.Meta = result.Meta
	response.JSON(rw)
}

// GetDetailTicket documentation
// @Summary			Get Detail Ticket
// @Description		API for get detail ticket
// @Tags			Ticket
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Success			200	{object}	domain.ResponseTicket
// @Success			400	{object}	wrapper.HTTPResponse
// @Success			404	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/ticket/{id} [get]
func (h *RestHandler) getDetailTicketByID(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TicketDeliveryREST:GetDetailTicketByID")
	var (
		err error
		id  int
	)

	defer func() {
		trace.SetTag("id", id)
		trace.Finish(tracer.FinishWithError(err))
	}()

	id, err = strconv.Atoi(restserver.URLParam(req, "id"))
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, helper.ErrorID).JSON(rw) //nolint:all
		return
	}

	data, err := h.uc.Ticket().GetDetailTicket(ctx, id)
	if err != nil {
		if err.Error() == helper.RecordNotFound {
			wrapper.NewHTTPResponse(http.StatusNotFound, err.Error()).JSON(rw) //nolint:all
			return
		}
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "success", data).JSON(rw)
}

// CreateTicket documentation
// @Summary			Create Ticket
// @Description		API for create ticket
// @Tags			Ticket
// @Accept			json
// @Produce			json
// @Param			data	body	domain.RequestTicket	true	"Body Data"
// @Success			200	{object}	domain.ResponseTicket
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/ticket [post]
func (h *RestHandler) createTicket(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TicketDeliveryREST:CreateTicket")
	var (
		err     error
		payload domain.RequestTicket
	)

	defer func() {
		trace.Log("payload", payload)
		trace.Finish(tracer.FinishWithError(err))
	}()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("ticket/save", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	res, err := h.uc.Ticket().CreateTicket(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusCreated, "success", res).JSON(rw)
}

// UpdateTicket documentation
// @Summary			Update Ticket
// @Description		API for update ticket
// @Tags			Ticket
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Param			data	body	domain.RequestTicket	true	"Body Data"
// @Success			200	{object}	domain.ResponseTicket
// @Success			400	{object}	wrapper.HTTPResponse
// @Success			404	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/ticket/{id} [put]
func (h *RestHandler) updateTicket(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TicketDeliveryREST:UpdateTicket")
	var (
		err     error
		payload domain.RequestTicket
		id      int
	)

	defer func() {
		trace.SetTag("id", id)
		trace.Log("payload", payload)
		trace.Finish(tracer.FinishWithError(err))
	}()

	id, err = strconv.Atoi(restserver.URLParam(req, "id"))
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, helper.ErrorID).JSON(rw) //nolint:all
		return
	}

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("ticket/save", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	payload.ID = id
	err = h.uc.Ticket().UpdateTicket(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "success").JSON(rw)
}

// DeleteTicket documentation
// @Summary			Delete Ticket
// @Description		API for delete ticket
// @Tags			Ticket
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Success			200	{object}	domain.ResponseTicket
// @Success			400	{object}	wrapper.HTTPResponse
// @Success			404	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/ticket/{id} [delete]
func (h *RestHandler) deleteTicket(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "TicketDeliveryREST:DeleteTicket")
	var (
		err error
		id  int
	)

	defer func() {
		trace.SetTag("id", id)
		trace.Finish(tracer.FinishWithError(err))
	}()

	id, err = strconv.Atoi(restserver.URLParam(req, "id"))
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, helper.ErrorID).JSON(rw) //nolint:all
		return
	}

	if err := h.uc.Ticket().DeleteTicket(ctx, id); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "success").JSON(rw)
}
