// Code generated by candi v1.20.0. DO NOT EDIT.

package repository

import (
	"sync"
	
	

	"github.com/golangid/candi/codebase/factory/dependency"
)

var (
	once sync.Once
)

// SetSharedRepository set the global singleton "RepoSQL" and "RepoMongo" implementation
func SetSharedRepository(deps dependency.Dependency) {
	once.Do(func() {
		setSharedRepoSQL(deps.GetSQLDatabase().ReadDB(), deps.GetSQLDatabase().WriteDB())
		// setSharedRepoMongo(deps.GetMongoDatabase().ReadDB(), deps.GetMongoDatabase().WriteDB())
		// setSharedRepoArango(deps.GetExtended("arangodb").(arango.ArangoDatabase).ReadDB(), deps.GetExtended("arangodb").(arango.ArangoDatabase).WriteDB())
	})
}
