// Code generated by candi v1.20.0.

package usecase

import (
	"context"

	"ticketing/internal/modules/ticket/domain"
	"ticketing/pkg/shared/repository"
	"ticketing/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
)

// TicketUsecase abstraction
type TicketUsecase interface {
	GetAllTicket(ctx context.Context, filter *domain.FilterTicket) (data domain.ResponseTicketList, err error)
	GetDetailTicket(ctx context.Context, id int) (data domain.ResponseTicket, err error)
	CreateTicket(ctx context.Context, data *domain.RequestTicket) (res domain.ResponseTicket, err error)
	UpdateTicket(ctx context.Context, data *domain.RequestTicket) (err error)
	DeleteTicket(ctx context.Context, id int) (err error)
}

type ticketUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	cache         interfaces.Cache
	// repoMongo     repository.RepoMongo
}

// NewTicketUsecase usecase impl constructor
func NewTicketUsecase(deps dependency.Dependency) (TicketUsecase, func(sharedUsecase common.Usecase)) {
	uc := &ticketUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
	}
	if redisPool := deps.GetRedisPool(); redisPool != nil {
		uc.cache = redisPool.Cache()
	}

	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
